### ISSUE TITLE
Won't respond to files with ? in name (supported by FS)

### ISSUE THREAD

**Issue by andrewhodel** [avoidwork/turtle.io#343]
```
touch webroot/jquery.easing.1.3.js?ver=3.8.3

node whateverYouCalledTurtleApp.js

wget server.tld/jquery.easing.1.3.js?ver=3.8.3
```

No response gets sent (same result with browser).

**Comment by andrewhodel** [comment]
OpenBSD 5.7 with default node pkg (10.35).

**Comment by avoidwork** [comment]
That's a query string embedded in the file name; why would you expect it to find it on disk?

**Comment by andrewhodel** [comment]
Because it is a file on the disk.

**Comment by avoidwork** [comment]
Yes, I understand that, but it's illogical. The problem exists by design, such that `req.url` runs through `url.parse()` (via external lib in this case), and then `parsed.pathname` is utilized to find a file on disk; this methodology removes a lot of surface area for attack vectors.

Seen at line: https://github.com/avoidwork/turtle.io/blob/master/src/turtleio.js#L1171

**Comment by avoidwork** [comment]
I'm always open to suggestions on how to accommodate workflows, as long as they don't regress other areas.

**Comment by andrewhodel** [comment]
It's not illogical, check if the file exists as a whole path (entire string) then if it does not you should parse it with url.parse()

It doesn't make sense to parse every url as a querystring when the base request and majority afterward (considering this is a file server, not a REST api) are going to be files.

There are plenty of cases where someone will wget an entire site and the filenames of files will include the querystring (because most websites work that way), if you don't do this then those all fail.

It's also worth the thought that for nginx, apache, lighttpd etc... this is the default behavior.

At the least when using your default sample app:

```
var server = require("turtle.io")();
server.start({
    default : "mysite.com",
    port    : 80,
    uid     : 100,
    root    : "/var/www",
    pages   : "errors",
    vhosts  : {
        "mysite.com"         : "mysite.com",
        "another-domain.com" : "another-domain.com"
    }
});
```

There is no querystring parsing needed, so why not count on it being files?

As it stands now, there's not even an error or notification of what's going on.  The request isn't even logged, for sure the request should go to the log before the response is made...

**Comment by avoidwork** [comment]
You assume much.

This is a generic server which behaves in such a way that it does afford API services, see [tenso](https://github.com/avoidwork/tenso), [cocoa](https://github.com/avoidwork/cocoa), & (rozu)[https://github.com/avoidwork/rozu].

I can easily change the function I linked to to test "with" and "without" the query string, but parsing happens first and is effectively required to get into the 99% concurrency range. The servers you list for comparison are simply dumb by design, and still slower on comparible hardware... I'm not trying to match their naive logic.

**Comment by avoidwork** [comment]
I may be misunderstanding the spec, but I'm pretty sure it's implemented properly:

https://tools.ietf.org/html/rfc3986#section-3.3

```
The path component contains data, usually organized in hierarchical
form, that, along with data in the non-hierarchical query component
(Section 3.4), serves to identify a resource within the scope of the
URI's scheme and naming authority (if any).  The path is terminated
by the first question mark ("?") or number sign ("#") character, or
by the end of the URI.
```

The query string is 3.4, and 'meta' information on the URI path.

However, if we go down this rabbit hole, how do you prepose the fragment is supported?

**Comment by andrewhodel** [comment]
Well let's first talk about the speed.

Are you telling me that it is faster to parse every request as a URI rather than:

```
if (fs.existsSync(path)) {
    // open file and return it
} else {
    // parse the uri
}
```

Also that says nothing about priority of a querystring over an existing file in the RFC quote, so it is not relevant.

Also, this is not a rabbit hole this is a technical issue.

**Comment by avoidwork** [comment]
I gotta pick this up in an hour. Lets not get hung up on 'how' and only focus on the concern you raised.

**Comment by andrewhodel** [comment]
I'll pick it up now:

```
fsStat x 50,670 ops/sec Â±3.11% (83 runs sampled)
parseUri x 44,119 ops/sec Â±0.70% (101 runs sampled)
Fastest is fsSta
```

```
var Benchmark = require('benchmark');
var suite = new Benchmark.Suite;
var url = require('url');
var fs = require('fs');

// add tests
var testUrl = 'https://github.com/avoidwork/turtle.io/test/hmm/file.ext?file=notreal&someothervar=asldkfjaslkdfjvlyhyieddsaflhkc';

suite.add('fsStat', function() {
	fs.existsSync(testUrl);
	
});
suite.add('parseUri', function() {
	url.parse(testUrl);
});

// add listeners
suite.on('cycle', function(event) {
  console.log(String(event.target));
});
suite.on('complete', function() {
  console.log('Fastest is ' + this.filter('fastest').pluck('name'));
});

// run async
suite.run({ 'async': true });
```

**Comment by avoidwork** [comment]
Well, if it was only concerned with files on disk that might matter... but it's not.

**Comment by andrewhodel** [comment]
You can't possibly define everyone's use case so it's better to support all in the fastest mode possible.

**Comment by avoidwork** [comment]
I can, and I did. The parsing is utilized for memoization centric code. I also have bad news for you; your bug is invalid. Windows doesn't allow `?` in a file name, and turtle.io runs on windows. If any of the servers you listed also run on windows, I guarantee you your edge case is not possible.

![screen shot 2015-07-09 at 3 34 21 pm](https://cloud.githubusercontent.com/assets/369698/8605059/839aad7c-2650-11e5-8567-5a3c210110d6.png)

You're the first person I've encountered in my entire career span (17yr) that has requested `?` be supported in a file name. I think you're doing it wrong.

**Comment by andrewhodel** [comment]
http://w3techs.com/technologies/overview/operating_system/all

GL, at least as long as it's open source I can just change or add 1 line (unlike Windows).

**Comment by avoidwork** [comment]
That's the beauty of it. You can also fork, add your addition & issue a PR, and if it doesn't greatly affect the siege results it'll be accepted.

I'm not going out of my way to support your odd usage, but I won't block it either.

**Comment by andrewhodel** [comment]
Seriously though you are already using lstat on the pathname before parsing the querystring, why not just support it?

**Comment by avoidwork** [comment]
I guess the context of this server would be useful: dev centric, prototype or even production worthy. Windows is an after thought that happened when some .net people became interested in it. It tries to afford everyone's workflow without colliding.

**Comment by avoidwork** [comment]
Answer: I need a few days off; been doing 'day job' and then 'oss job' in the evening. I pointed you to the line in code to change, go nuts.

**Comment by avoidwork** [comment]
The parsing happens in the `decorate()` middleware, first one in the queue i think, because the `etag()` middleware needs the vhost, which is taken from the parsed results.

**Comment by andrewhodel** [comment]
For what it's worth there's also a parsing issue with parsing ascii codes in the url:

```
index.html%3Fp=12.html
```

That will fail with no response, why not at least console.log the error if there is one instead of just ending?  That's giving up...

It should convert that ascii code to a ?

That's what it really is.

**Comment by andrewhodel** [comment]
Also it's not my bug, it's a problem with my use case which would:

A) improve your software to support this use case

B) not take any cycles, nor create any problems

It's like a free functionality.

**Comment by avoidwork** [comment]
I was thinking about that this afternoon when you raised the issue. It's not decoding the query string prior to the the attempting parsing; there's probably no error handling for that issue, and it falls into a `Promise` black hole.

It's a legit bug to fix.

**Comment by avoidwork** [comment]
Looks like it's a node.js bug, as the offending line is: https://github.com/avoidwork/keigai/blob/master/src/utility.js#L596

**Comment by andrewhodel** [comment]
This fixes it properly:

https://github.com/andrewhodel/turtle.io/commit/0699d06a11dd8042547c3fba7804183a817e5f43

**Comment by avoidwork** [comment]
Thanks, but I got it in the underlying lib that sets `req.parsed` such that all middleware can utilize the correct values.

https://github.com/avoidwork/keigai/issues/80

**Comment by avoidwork** [comment]
"Seriously though you are already using lstat on the pathname before parsing the querystring, why not just support it?"

You can support it by modifying the `lpath` test to support with & without `?`, otherwise by simply changing it to use `parsed.path` you'll lose support for files that do not have `?` in their name.

**Comment by andrewhodel** [comment]
The code I wrote did not change it to use parsed.path, it converted the hexadecimal characters to binary then in the case of hexadecimal characters looked for a filename rather than parse a query string.  It actually still works normally with files that do not have a ? in their name.

**Comment by andrewhodel** [comment]
There's also this in the RFC:

```

3.4. Query Component

   The query component is a string of information _______to be interpreted by
   the resource.________

      query         = *uric

   Within a query component, the characters ";", "/", "?", ":", "@",
   "&", "=", "+", ",", and "$" are reserved.
```

https://www.ietf.org/rfc/rfc2396.txt

So in total honesty per the RFC spec it's whatever you want to do.  Considering there's no speed difference (we've proven that) I don't see why not to include that style parsing like every major server does.

**Comment by avoidwork** [comment]
Put it in the ride spot of the pipeline and it's a welcome addition; that's literally the end.

**Comment by avoidwork** [comment]
There is a function `pipeline()`; either it belongs there or the right spot is `decorate()` or somewhere in between, depending on how you feel about it's role.
